apiVersion: apps/v1
kind: Deployment
metadata:
  name: dss
  labels:
    app: dss
spec:
  selector:
    matchLabels:
      app: dss
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: dss
    spec:
      containers:
      - name: dss-container
        image: k8scrvidchaindev.azurecr.io/dss:v5.8
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: dss-service
  labels:
    app: dss
spec:
  ports:
  - port: 8090
    targetPort: 8080
  selector:
    app: dss

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dss-ingress
  namespace: development
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - dev.vidchain.net
    secretName: tls-secret-development
  rules:
  - host: dev.vidchain.net
    http:
      paths:
      - path: /dss/(.*)
        backend:
          serviceName: dss-service
          servicePort: 8090